baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'STELLA'
theme = 'blackburn'

[params]
  custom_css = ["css/my.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
