baseURL = '/'
languageCode = 'en-us'
title = 'STELLA'
author = "STELLA"
theme = 'blackburn'
paginate = 10
copyright = "&copy; 2023. All rights reserved."
enableInlineShortcodes = true
relativeURLs = "True"
[indexes]
  tag = "tags"
  topic = "topics"

  
[params]
  custom_css = ["css/my.css"]
  subtitle = "Infrastructures for Living Labs"
  dateFormat = "02 Jan 2006"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
  # Shown in the side menu.
    [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "main"
    url = "/home/"
  [[menu.main]]
    name = "People"
    weight = 2
    identifier = "people"
    url = "/people/"
  [[menu.main]]
    name = "Code"
    weight = 3
    identifier = "code"
    url = "/code/"
  [[menu.main]]
    name = "Funding"
    weight = 4
    identifier = "funding"
    url = "/funding/"
  [[menu.main]]
    name = "Blog"
    weight = 5
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Publications"
    weight = 6
    identifier = "publications"
    url = "/publications/"
  [[menu.main]]
    name = "About"
    weight = 7
    identifier = "about"
    url = "/about"
