baseURL = 'https://stella-project.org/stella-project.github.io/'
languageCode = 'en-us'
title = 'STELLA'
theme = 'blackburn'
paginate = 10
enableInlineShortcodes = true
canonifyurls = true

[indexes]
  tag = "tags"
  topic = "topics"

  
[params]
  custom_css = ["https://stella-project.org/stella-project.github.io/css/my.css"]
  subtitle = "Infrastructures for Living Labs"
  dateFormat = "02 Jan 2006"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
  # Shown in the side menu.
    [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "main"
    url = "/home/"
  [[menu.main]]
    name = "People"
    weight = 2
    identifier = "people"
    url = "/people/"
  [[menu.main]]
    name = "Code"
    weight = 3
    identifier = "code"
    url = "/code/"
  [[menu.main]]
    name = "Blog"
    weight = 4
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Publications"
    weight = 5
    identifier = "publications"
    url = "/publications/"
  [[menu.main]]
    name = "About"
    weight = 6
    identifier = "about"
    url = "/about"
